### ISSUE TITLE
What are the "n_frames files", and a small question about "annotation_dir_path "

### ISSUE THREAD

**Issue by BarakBat** [kenshohara/3D-ResNets-PyTorch#107]
Hi, two small questions:
1. What are the "n_frames files"? why do we want to make them?
2. I didn't understand where the directory with all the annotation, as called in the command: "annotation_dir_path ", suppose to be created because I don't have any directory that includes: "brush_hair_test_split1.txt" or something like that.

I'll be happy for your help.
Thanks.

**Comment by lhyfst** [comment]
@Esaada Have you figured out what are the n_frames files? I am confused, too.
