### ISSUE TITLE
Finetune, Where does the the freeze happens

### ISSUE THREAD

**Issue by BarakBat** [kenshohara/3D-ResNets-PyTorch#129]
Hi I'm trying to understand where does the freeze happens, you said your finetuning only fc and last conv, but I can't see where it happens?
I can see that youre getting the params for finetuning, but not freezing anything..

**Comment by ZilinGao** [comment]
In function models/resnet.py/get_fine_tuning_parameters ,  if the parametric layers are not within the range of  ft_begin_index to 5, their lr will be set to 0, which means cannot to optimized.

**Comment by BarakBat** [comment]
Thanks
