### ISSUE TITLE
Train from scratch on UCF101 using ResNet18 and get 10% gain without doing anything

### ISSUE THREAD

**Issue by BestJuly** [kenshohara/3D-ResNets-PyTorch#130]
I train and evaluate the code and get 10% gain without changing anything. Here is my process:
1. Parse video data using codes from READ.ME.
2. Train the model using `python3 main.py --root_path ./datasets/ --video_path UCF101/jpg --annotation_path ucf101_01.json --result_path results --dataset ucf101 --model resnet --model_depth 18 --n_classes 101 --batch_size 16` and get the model result `datasets/desults/save_200.pth`.
3. Test the dataset using `python3 main.py --root_path ./datasets/ --video_path UCF101/jpg --annotation_path ucf101_01.json --result_path results --dataset ucf101 --resume_path results/save_200.pth --model resnet --model_depth 18 --n_classes 101 --batch_size 16 --no_train --test ` and get the result in `val.json` and the command window says the clip accuracy is 0.346.
4. Get the accuracy using `eval_ucf101.py` to compare `ucf101_01.json` with `val.json` and the top1 accuracy for video is 52.66%, which is about 10% over 42.4% (reported in the paper).

I only use UCF101 split_01 so there are no overlap videos in train and test data. It is a little bit strange, and is it because in the paper, the training procedure did not last for 200 epochs?
My platform is Pytorch 0.4 and I only modified one place to avoid the error, which is reported in another issue.

**Comment by slighting666** [comment]
@BestJuly 
Hi, I got the accuracy of val.log, but I want to calculate the accuracy of video level, where can I get the val.json file and how to use eval_ucf101.py?

**Comment by BestJuly** [comment]
@fmahoudeau Sorry to see the message late, for other splits, the accuracy is similar when using pre-trained models. So I guess it is OK for that. I asked the author and He said he had not tried different settings, that is why the reported results are not very high.

**Comment by slighting666** [comment]
excuse..
Hi, I got the accuracy of val.log, but I want to calculate the accuracy of video level, where can I get the val.json file and how to use eval_ucf101.py?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"BestJuly"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月10日(星期五) 中午1:33
收件人:&nbsp;"kenshohara/3D-ResNets-PyTorch"<3D-ResNets-PyTorch@noreply.github.com&gt;;
抄送:&nbsp;"slighting"<1149745774@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [kenshohara/3D-ResNets-PyTorch] Train from scratch on UCF101 using ResNet18 and get 10% gain without doing anything (#130)




@fmahoudeau Sorry to see the message late, for other splits, the accuracy is similar when using pre-trained models. So I guess it is OK for that. I asked the author and He said he had not tried different settings, that is why the reported results are not very high.

**Comment by BestJuly** [comment]
@slighting666 
I write some codes to use `eval_ucf101.py`. You can put the following codes at the end of this file and then run.
```
if __name__=="__main__":
  test_class = UCFclassification(ground_truth_filename='../datasets/ucf101_01.json', prediction_filename='../datasets/results/val.json', verbose=True, top_k=1)
  test_class.evaluate()
```

**Comment by slighting666** [comment]
Ok, thank you, I ran main.py, but I only got the following file.As shown in the email, how can I get val.json?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"BestJuly"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月10日(星期五) 中午1:37
收件人:&nbsp;"kenshohara/3D-ResNets-PyTorch"<3D-ResNets-PyTorch@noreply.github.com&gt;;
抄送:&nbsp;"slighting"<1149745774@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [kenshohara/3D-ResNets-PyTorch] Train from scratch on UCF101 using ResNet18 and get 10% gain without doing anything (#130)




@slighting666
 I write some codes to use eval_ucf101.py. You can put the following codes at the end of this file and then run.
 if __name__=="__main__":   test_class = UCFclassification(ground_truth_filename='../datasets/ucf101_01.json', prediction_filename='../datasets/results/val.json', verbose=True, top_k=1)   test_class.evaluate()

**Comment by BestJuly** [comment]
The log files are generated when training. To test, have you run the step 3? When done, you should get `val.json` somewhere (you can check your code to find the location).
> `python3 main.py --root_path ./datasets/ --video_path UCF101/jpg --annotation_path ucf101_01.json --result_path results --dataset ucf101 --resume_path results/save_200.pth --model resnet --model_depth 18 --n_classes 101 --batch_size 16 --no_train --test `

**Comment by slighting666** [comment]
Ok, thank you. Could you help me see what I missed?In the attachment are all the files generated by running main.py.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"BestJuly"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月10日(星期五) 中午1:45
收件人:&nbsp;"kenshohara/3D-ResNets-PyTorch"<3D-ResNets-PyTorch@noreply.github.com&gt;;
抄送:&nbsp;"slighting"<1149745774@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [kenshohara/3D-ResNets-PyTorch] Train from scratch on UCF101 using ResNet18 and get 10% gain without doing anything (#130)




The log files are generated when training. To test, have you run the step 3? When done, you should get val.json somewhere (you can check your code to find the location).
  
python3 main.py --root_path ./datasets/ --video_path UCF101/jpg --annotation_path ucf101_01.json --result_path results --dataset ucf101 --resume_path results/save_200.pth --model resnet --model_depth 18 --n_classes 101 --batch_size 16 --no_train --test

**Comment by slighting666** [comment]
Sorry to interrupt, To test, have you run the step 3? &nbsp;&nbsp; What do you mean, step 3？
thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"BestJuly"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月10日(星期五) 中午1:45
收件人:&nbsp;"kenshohara/3D-ResNets-PyTorch"<3D-ResNets-PyTorch@noreply.github.com&gt;;
抄送:&nbsp;"slighting"<1149745774@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [kenshohara/3D-ResNets-PyTorch] Train from scratch on UCF101 using ResNet18 and get 10% gain without doing anything (#130)




The log files are generated when training. To test, have you run the step 3? When done, you should get val.json somewhere (you can check your code to find the location).
  
python3 main.py --root_path ./datasets/ --video_path UCF101/jpg --annotation_path ucf101_01.json --result_path results --dataset ucf101 --resume_path results/save_200.pth --model resnet --model_depth 18 --n_classes 101 --batch_size 16 --no_train --test

**Comment by BestJuly** [comment]
@slighting666 You are using emails to reply, which makes it wired. If you check this issue online, you can see my quotation. And those steps 1, 2, 3, 4 were stated when I opened this issue.

**Comment by slighting666** [comment]
@BestJuly 
I don't quite understand the meaning of step 3, how do I run step 3 after I have trained step 2? When I run step 3, what are the differences between opts. Py and step 2

**Comment by slighting666** [comment]
@BestJuly 
ok，I followed your instructions in step 3, but I got an error:
Traceback (most recent call last):
  File "D:/github/3D resnet/3D resnet/main.py", line 163, in <module>
    test.test(test_loader, model, opt, test_data.class_names)
  File "D:\github\3D resnet\3D resnet\test.py", line 52, in test
    test_results, class_names)
  File "D:\github\3D resnet\3D resnet\test.py", line 20, in calculate_video_results
    'label': class_names[locs[i]],
KeyError: tensor(1)
can you help me？

**Comment by anson-07** [comment]
`[INIT] Loaded annotations from validation subset.
        Number of ground truth instances: 3783
        Number of predictions: 37820
[RESULTS] Performance on ActivityNet untrimmed video classification task.
        Error@1: 0.8699444885011896`

For some reason the number of predictions are so much higher and the error seems to be so high when I tested using resnext-101-kinetics-ucf101_split1.pth on UCF101 dataset using the command line below. Is this normal? 

`# python main.py --root_path ./datasets/ --video_path Action_Recognition_DATASETS\UCF101\UCF-101-JPG --annotation_path ucf101_01.json --result_path results --dataset ucf101 --resume_path resnext-101-kinetics-ucf101_split1.pth --model resnext --model_depth 101 --resnet_shortcut B --resnext_cardinality 32 --n_classes 101 --batch_size 16 --no_train --test`

Please help... Sorry I know this issue has been closed but I would like to ask for help because I followed and inserted your code in the `eval_ucf101.py` and the code does seem make sense to me. But the results seem to not make sense...

`if __name__=="__main__":
  test_class = UCFclassification(ground_truth_filename='../datasets/ucf101_01.json', prediction_filename='../datasets/results/val.json', verbose=True, top_k=1)
  test_class.evaluate()`

**Comment by anson-07** [comment]
> @BestJuly
> ok，I followed your instructions in step 3, but I got an error:
> Traceback (most recent call last):
> File "D:/github/3D resnet/3D resnet/main.py", line 163, in
> test.test(test_loader, model, opt, test_data.class_names)
> File "D:\github\3D resnet\3D resnet\test.py", line 52, in test
> test_results, class_names)
> File "D:\github\3D resnet\3D resnet\test.py", line 20, in calculate_video_results
> 'label': class_names[locs[i]],
> KeyError: tensor(1)
> can you help me？

You have to modify the `calculate_video_results` function like this to avoid errors, added `.item()` and `.numpy().tolist()` to avoid some unwanted errors:

```
def calculate_video_results(output_buffer, video_id, test_results, class_names):
    video_outputs = torch.stack(output_buffer)
    average_scores = torch.mean(video_outputs, dim=0)
    sorted_scores, locs = torch.topk(average_scores, k=10)

    video_results = []
    for i in range(sorted_scores.size(0)):
        video_results.append({
            # added .item().numpy()
            'label': class_names[locs[i].item()],
            # added .numpy().tolist()
            'score': sorted_scores[i].numpy().tolist()
        })

    test_results['results'][video_id] = video_results
```

**Comment by anson-07** [comment]
> @slighting666
> I write some codes to use `eval_ucf101.py`. You can put the following codes at the end of this file and then run.
> 
> ```
> if __name__=="__main__":
>   test_class = UCFclassification(ground_truth_filename='../datasets/ucf101_01.json', prediction_filename='../datasets/results/val.json', verbose=True, top_k=1)
>   test_class.evaluate()
> ```

```
[INIT] Loaded annotations from validation subset.
        Number of ground truth instances: 3783
        Number of predictions: 37820
[RESULTS] Performance on ActivityNet untrimmed video classification task.
        Error@1: 0.8699444885011896
```

For some reason the number of predictions are so much higher and the error seems to be so high when I tested using resnext-101-kinetics-ucf101_split1.pth on UCF101 dataset using the command line below. Is this normal? 

`python main.py --root_path ./datasets/ --video_path Action_Recognition_DATASETS\UCF101\UCF-101-JPG --annotation_path ucf101_01.json --result_path results --dataset ucf101 --resume_path resnext-101-kinetics-ucf101_split1.pth --model resnext --model_depth 101 --resnet_shortcut B --resnext_cardinality 32 --n_classes 101 --batch_size 16 --no_train --test`

Please help... Sorry I know this issue has been closed but I would like to ask for help because I followed and inserted your code in the `eval_ucf101.py` and the code does seem make sense to me. But the results seem to not make sense...

```
if __name__=="__main__":
  test_class = UCFclassification(ground_truth_filename='../datasets/ucf101_01.json', prediction_filename='../datasets/results/val.json', verbose=True, top_k=1)
  test_class.evaluate()
```

**Comment by anson-07** [comment]
```
def test(data_loader, model, opt, class_names):
    print('test')

    model.eval()

    batch_time = AverageMeter()
    data_time = AverageMeter()

    end_time = time.time()
    output_buffer = []
    previous_video_id = ''
    test_results = {'results': {}}
    for i, (inputs, targets) in enumerate(data_loader):
        data_time.update(time.time() - end_time)
        with torch.no_grad():  # added this and removed volatile=True from the inputs variable
            inputs = Variable(inputs)
            outputs = model(inputs)
        if not opt.no_softmax_in_test:
            # print(outputs.size())  # torch.Size([16, 101])
            outputs = F.softmax(outputs, dim=1)  # added dim as argument
    ...
```
Ok at the `test()` function, I realized I put the argument of `softmax()` as `dim=0` which is wrong after I checked the `size` of the `outputs`, so I changed to `dim=1` and I got the results below. 
```
[INIT] Loaded annotations from validation subset.
        Number of ground truth instances: 3783
        Number of predictions: 37820
[RESULTS] Performance on ActivityNet untrimmed video classification task.
        Error@1: 0.09886333597673802
```
The number of predictions are still so much higher but the error went down so much, seems reasonable for a fine-tuned ResNeXt-101?

**Comment by BestJuly** [comment]
@anson-07 Hi, I think the number of prediction is corresponding to the number of tested videos, so it is fine that this number is high. On UCF101 datasets, if you fine-tune pre-trained models, it is very easy to get an accuracy of more than 90%. Therefore, it is normal that the top1 error is 0.0988.

**Comment by anson-07** [comment]
> @anson-07 Hi, I think the number of prediction is corresponding to the number of tested videos, so it is fine that this number is high. On UCF101 datasets, if you fine-tune pre-trained models, it is very easy to get an accuracy of more than 90%. Therefore, it is normal that the top1 error is 0.0988.

Alright thank you very much.
