### ISSUE TITLE
Error while loading weights

### ISSUE THREAD

**Issue by skrish13** [kenshohara/3D-ResNets-PyTorch#15]
`KeyError: 'unexpected key "module.features.conv0.weight" in state_dict'`

I'm using `densenet-201-kinetics.pth` file with the `densenet.py` file from models folder.

```
net = densenet.densenet201(sample_size=64, sample_duration=30, num_classes=400)
pretrained_weights = torch.load(pretrained_path)
net.load_state_dict(pretrained_weights['state_dict'])
```

**Comment by skrish13** [comment]
I'm not using the repository as it is. I've taken the `densenet.py` file from the models folder and doing the following after downloading the weights from google drive. Can you try this simply in an ipython or a small python script?
```
import densenet
net = densenet.densenet201(sample_size=64, sample_duration=30, num_classes=400)
pretrained_weights = torch.load('densenet-201-kinetics.pth')
net.load_state_dict(pretrained_weights['state_dict'])
```

From what I saw in the codebase, essentially this is what is being done. The `model.py` calls the specific file from `models\specific_network.py` to create the class object. Then if the flag `opt.pretrain_path` is set, then it loads the pretrained weights from disk and assigns into the model weights. Not sure why its not working though? I think I might be missing something trivial?

**Comment by kenshohara** [comment]
I trained the model using 16x112x112 inputs (i.e. sample_size=112, sample_duration=16).
So, if you use my pretrained models, you have to use the input sizes.

**Comment by skrish13** [comment]
Thats correct. But the code doesn't use sample_size and sample_duration for creating the network. It's only used during forward prop (PyTorch is great). So irrespective of what value we give the network should load pretrained weights without any error... Having said that, let me check if it works with that values anyways, I might as well be making some mistake.

**Comment by kenshohara** [comment]
I could reproduce the error and solve it.
I trained the model using GPUs.
So, the model is wrapped by nn.DataParallel.
You have to wrap the model using nn.DataParallel before ```load_state```.

```
import torch
from torch import nn
import densenet
net = densenet.densenet201(sample_size=64, sample_duration=30, num_classes=400)

net = nn.DataParallel(net, device_ids=None)

pretrained_weights = torch.load('densenet-201-kinetics.pth')
net.load_state_dict(pretrained_weights['state_dict'])
```

**Comment by skrish13** [comment]
woohoo. thanks a lot! :D
