### ISSUE TITLE
n_samples_for_each_video

### ISSUE THREAD

**Issue by Bryce1010** [kenshohara/3D-ResNets-PyTorch#161]
Thanks for your nice work!
But I didn't figure out the usage of "n_samples_for_each_videos", can you explain it?  
Thanks a lot.

**Comment by iuhiyuh** [comment]
就是一个视频里采几个样本，比如n_samples=3，那么就会从一个视频里按照设置的sample_duration数量，循环的从视频里采3个样本

**Comment by Huixxi** [comment]
I agree with what the upper said, just translate it into English for more readers:
"Just how many samples you sample from one video, that if set `n_samples_for_each_videos = 3`, then, you will get 3 samples sampled circularly from that video, each sample has a `sample_duration` length."
