### ISSUE TITLE
Error after running `video_jpg_ucf101_hmdb51.py:UnicodeDecodeError: 'utf-8' can't decode byte 0x8c in position 3864: invalid start byte

### ISSUE THREAD

**Issue by shadsakib** [kenshohara/3D-ResNets-PyTorch#183]
I'm trying to train the model on hmdb101 dataset. I downloaded everything and ran utils/video_jpg_ucf101_hmdb51.py.
After running for a while and converting some videos into jpgs it gives the following error:
``UnicodeDecodeError: 'utf-8' can't decode byte 0x8c in position 3864: invalid start byte

**Comment by Deepanshu-beep** [comment]
Hey, @shadsakib did you find out what's causing the issue?
