### ISSUE TITLE
R2+1D pretrained models

### ISSUE THREAD

**Issue by DAVEISHAN** [kenshohara/3D-ResNets-PyTorch#191]
Hi, 

Please, upload pretrained models for R2+1D for 18 and 34 layers. Excited to hear back from you!

And thanks a lot for providing R3D pretrained models on Kinetics, Moments, and STAIR actions!

**Comment by kenshohara** [comment]
I uploaded r2p1d18_K_200ep.pth and r2p1d34_K_200ep.pth.
Please confirm and try them!
