### ISSUE TITLE
Are pretrained models of ResNext-101(64-f) architecture available?

### ISSUE THREAD

**Issue by Fazlik995** [kenshohara/3D-ResNets-PyTorch#194]
Hi, thanks for an awesome work.

Have you obtained pretrained models of ResNext-101(64-f) architecture?

If so, could you please add that models as well.

Thank you.

**Comment by kenshohara** [comment]
The model resnext-101-64f-kinetics.pth already exist in my Google Drive.

**Comment by Fazlik995** [comment]
I mean for K+M pretrained model, not for Kinetics-400

I think in your google drive, you provided pretrained models only for ResNet model, not ResNext, right?

**Comment by kenshohara** [comment]
We did not try ResNeXt models on Kinetics-700 and Moments in Time datasets.
You have to train the models on your own if you want to use the models.
