### ISSUE TITLE
The downsample branch parameters of resnet18 pretrain model is missing

### ISSUE THREAD

**Issue by BannyStone** [kenshohara/3D-ResNets-PyTorch#20]
I cannot find the downsample branch parameters in resnet18 pretrain model: resnet-18-kinetics.pth.
These are all the keys in pretrain model state_dict:
-------------------------------------------------------
module.conv1.weight
module.bn1.weight
module.bn1.bias
module.bn1.running_mean
module.bn1.running_var
module.layer1.0.conv1.weight
module.layer1.0.bn1.weight
module.layer1.0.bn1.bias
module.layer1.0.bn1.running_mean
module.layer1.0.bn1.running_var
module.layer1.0.conv2.weight
module.layer1.0.bn2.weight
module.layer1.0.bn2.bias
module.layer1.0.bn2.running_mean
module.layer1.0.bn2.running_var
module.layer1.1.conv1.weight
module.layer1.1.bn1.weight
module.layer1.1.bn1.bias
module.layer1.1.bn1.running_mean
module.layer1.1.bn1.running_var
module.layer1.1.conv2.weight
module.layer1.1.bn2.weight
module.layer1.1.bn2.bias
module.layer1.1.bn2.running_mean
module.layer1.1.bn2.running_var
module.layer2.0.conv1.weight
module.layer2.0.bn1.weight
module.layer2.0.bn1.bias
module.layer2.0.bn1.running_mean
module.layer2.0.bn1.running_var
module.layer2.0.conv2.weight
module.layer2.0.bn2.weight
module.layer2.0.bn2.bias
module.layer2.0.bn2.running_mean
module.layer2.0.bn2.running_var
module.layer2.1.conv1.weight
module.layer2.1.bn1.weight
module.layer2.1.bn1.bias
module.layer2.1.bn1.running_mean
module.layer2.1.bn1.running_var
module.layer2.1.conv2.weight
module.layer2.1.bn2.weight
module.layer2.1.bn2.bias
module.layer2.1.bn2.running_mean
module.layer2.1.bn2.running_var
module.layer3.0.conv1.weight
module.layer3.0.bn1.weight
module.layer3.0.bn1.bias
module.layer3.0.bn1.running_mean
module.layer3.0.bn1.running_var
module.layer3.0.conv2.weight
module.layer3.0.bn2.weight
module.layer3.0.bn2.bias
module.layer3.0.bn2.running_mean
module.layer3.0.bn2.running_var
module.layer3.1.conv1.weight
module.layer3.1.bn1.weight
module.layer3.1.bn1.bias
module.layer3.1.bn1.running_mean
module.layer3.1.bn1.running_var
module.layer3.1.conv2.weight
module.layer3.1.bn2.weight
module.layer3.1.bn2.bias
module.layer3.1.bn2.running_mean
module.layer3.1.bn2.running_var
module.layer4.0.conv1.weight
module.layer4.0.bn1.weight
module.layer4.0.bn1.bias
module.layer4.0.bn1.running_mean
module.layer4.0.bn1.running_var
module.layer4.0.conv2.weight
module.layer4.0.bn2.weight
module.layer4.0.bn2.bias
module.layer4.0.bn2.running_mean
module.layer4.0.bn2.running_var
module.layer4.1.conv1.weight
module.layer4.1.bn1.weight
module.layer4.1.bn1.bias
module.layer4.1.bn1.running_mean
module.layer4.1.bn1.running_var
module.layer4.1.conv2.weight
module.layer4.1.bn2.weight
module.layer4.1.bn2.bias
module.layer4.1.bn2.running_mean
module.layer4.1.bn2.running_var
module.fc.weight
module.fc.bias
----------------------------------------
No downsample branch parameters in the above keys.

**Comment by BannyStone** [comment]
Is that because the pre-trained model is equipped with type A shortcut?

**Comment by kenshohara** [comment]
Yes, the downsampling of type A shortcut is performed by avg_pool3d with stride 2, which does not include any parameters.
https://github.com/kenshohara/3D-ResNets-PyTorch/blob/master/models/resnet.py#L25

So, the pretrained model does not include such parameters.

**Comment by BannyStone** [comment]
Thank you for your response
