### ISSUE TITLE
Cannot load the pretrained state_dict

### ISSUE THREAD

**Issue by DawnChou** [kenshohara/3D-ResNets-PyTorch#206]
I set the model as resnet-18 and use r3d18_KM_200ep.pth to pretrain it. However, it seems that I cannot load any parameters. Here is the error:
`loading pretrained model pretrain/r3d18_KM_200ep.pth 

Traceback (most recent call last):
  File "main.py", line 385, in <module>
    main(opt)
  File "main.py", line 314, in main
    opt.n_finetune_classes)
  File "/home/zouyiping/C3D_ELM/model.py", line 106, in load_pretrained_model
    model.load_state_dict(pretrain['state_dict'])
  File "/home/zouyiping/software/python3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))

RuntimeError: Error(s) in loading state_dict for ResNet:
Missing key(s) in state_dict: "conv1.weight", "bn1.weight", "bn1.bias", "bn1.running_mean", "bn1.running_var", "layer1.0.conv1.weight", "layer1.0.bn
1.weight", "layer1.0.bn1.bias", "layer1.0.bn1.running_mean", "layer1.0.bn1.running_var", "layer1.0.conv2.weight", "layer1.0.bn2.weight", "layer1.0.bn2.bias"
, "layer1.0.bn2.running_mean", "layer1.0.bn2.running_var", "layer1.1.conv1.weight", "layer1.1.bn1.weight", "layer1.1.bn1.bias", "layer1.1.bn1.running_mean",
 "layer1.1.bn1.running_var", "layer1.1.conv2.weight", "layer1.1.bn2.weight", "layer1.1.bn2.bias", "layer1.1.bn2.running_mean", "layer1.1.bn2.running_var", "
layer2.0.conv1.weight", "layer2.0.bn1.weight", "layer2.0.bn1.bias", "layer2.0.bn1.running_mean", "layer2.0.bn1.running_var", "layer2.0.conv2.weight", "layer
2.0.bn2.weight", "layer2.0.bn2.bias", "layer2.0.bn2.running_mean", "layer2.0.bn2.running_var", "layer2.0.downsample.0.weight", "layer2.0.downsample.1.weight
", "layer2.0.downsample.1.bias", "layer2.0.downsample.1.running_mean", "layer2.0.downsample.1.running_var", "layer2.1.conv1.weight", "layer2.1.bn1.weight", 
"layer2.1.bn1.bias", "layer2.1.bn1.running_mean", "layer2.1.bn1.running_var", "layer2.1.conv2.weight", "layer2.1.bn2.weight", "layer2.1.bn2.bias", "layer2.1
.bn2.running_mean", "layer2.1.bn2.running_var", "layer3.0.conv1.weight", "layer3.0.bn1.weight", "layer3.0.bn1.bias", "layer3.0.bn1.running_mean", "layer3.0.
bn1.running_var", "layer3.0.conv2.weight", "layer3.0.bn2.weight", "layer3.0.bn2.bias", "layer3.0.bn2.running_mean", "layer3.0.bn2.running_var", "layer3.0.do
wnsample.0.weight", "layer3.0.downsample.1.weight", "layer3.0.downsample.1.bias", "layer3.0.downsample.1.running_mean", "layer3.0.downsample.1.running_var",
 "layer3.1.conv1.weight", "layer3.1.bn1.weight", "layer3.1.bn1.bias", "layer3.1.bn1.running_mean", "layer3.1.bn1.running_var", "layer3.1.conv2.weight", "lay
er3.1.bn2.weight", "layer3.1.bn2.bias", "layer3.1.bn2.running_mean", "layer3.1.bn2.running_var", "layer4.0.conv1.weight", "layer4.0.bn1.weight", "layer4.0.b
n1.bias", "layer4.0.bn1.running_mean", "layer4.0.bn1.running_var", "layer4.0.conv2.weight", "layer4.0.bn2.weight", "layer4.0.bn2.bias", "layer4.0.bn2.runnin
g_mean", "layer4.0.bn2.running_var", "layer4.0.downsample.0.weight", "layer4.0.downsample.1.weight", "layer4.0.downsample.1.bias", "layer4.0.downsample.1.ru
nning_mean", "layer4.0.downsample.1.running_var", "layer4.1.conv1.weight", "layer4.1.bn1.weight", "layer4.1.bn1.bias", "layer4.1.bn1.running_mean", "layer4.
1.bn1.running_var", "layer4.1.conv2.weight", "layer4.1.bn2.weight", "layer4.1.bn2.bias", "layer4.1.bn2.running_mean", "layer4.1.bn2.running_var", "fc.weight
", "fc.bias". 
Unexpected key(s) in state_dict: "", "ict", "er". `

Can anybody tell me how to solve it??? Thanks in advance!

**Comment by DawnChou** [comment]
The problem has solved

**Comment by TitaniumOne** [comment]
Hi, I meet the same problem, could you please share the solutions? Thanks!!!

**Comment by TitaniumOne** [comment]
> 
> 
> The problem has solved

Hi, I meet the same problem, could you please share the solutions? Thanks!!!

**Comment by DawnChou** [comment]
> > The problem has solved
> 
> Hi, I meet the same problem, could you please share the solutions? Thanks!!!

It's been a long time and I cannot remember it clearly. Sorry. But I remember it was because there was something wrong in my load_dict function (I changed it in several codes, not as same as the original.) After I deleted what I revised, the problem could be solved. Maybe you can check your code again, or you can just run the part of loading state_dict to test and find the problem.

**Comment by kentaroy47** [comment]
`model.load_state_dict(pretrain['state_dict'], strict=False)`

this solved my error.
