### ISSUE TITLE
avi failed to generate jpg

### ISSUE THREAD

**Issue by N00k0428** [kenshohara/3D-ResNets-PyTorch#236]
python -m generate_video_jpgs "D:\\opt\\mp4"  "D:\\opt\\jpg"  activitynet
no result and  is no error message.
I unzip UCF101.rar to D:\\opt\\mp4.

How should I solve the problem? Thinks！

**Comment by guilhermesurek** [comment]
Hi. I think you should use this way:
`python -m util_scripts.generate_video_jpgs D:\opt\mp4 D:\opt\jpg ucf101`
Are you running UCF101 or ActivityNet?
Check if you are running from the root, main.py should be visible.
