### ISSUE TITLE
KeyError of distributed training

### ISSUE THREAD

**Issue by byrsongyuxin** [kenshohara/3D-ResNets-PyTorch#244]
(py37)Traceback (most recent call last):
  File "main.py", line 415, in <module>
    opt = get_opt()
  File "main.py", line 72, in get_opt
    opt.dist_rank = int(os.environ["OMPI_COMM_WORLD_RANK"])
  File "/home/wuming/anaconda3/envs/action/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'OMPI_COMM_WORLD_RANK'

**Comment by byrsongyuxin** [comment]
CUDA_VISIBLE_DEVICES=0,1 python main.py \
--root_path /dssg/syx/action-recognition/data \
--video_path /dssg/syx/action-recognition/data/UCF101/UCF-101-jpg \
--annotation_path /dssg/syx/action-recognition/data/UCF101/ucf101_01.json \
--result_path /home/wuming/syx/action-recognition/3D-ResNets-PyTorch-master/result \
--dataset ucf101 --n_classes 101 --n_pretrain_classes 700 \
--pretrain_path /home/wuming/syx/action-recognition/3D-ResNets-PyTorch-master/pretrain/r3d50_K_200ep.pth \
--ft_begin_module fc \
--model resnet --model_depth 50 \
--batch_size 128 --n_threads 4 --checkpoint 5 \
--batchnorm_sync --distributed

**Comment by byrsongyuxin** [comment]
I replace the PMI_RANK to OMPI_COMM_WORLD_RANK

**Comment by WUSHUANGPPP** [comment]
Could you please tell us how to run distributed training? I met same error with you,but replace PIM_RANK not work for me.....@byrsongyuxin Thank you very much!
