### ISSUE TITLE
generate_video_jpgs.py arguments are required error

### ISSUE THREAD

**Issue by EmirhanToprak** [kenshohara/3D-ResNets-PyTorch#247]
Hi, im getting the error that dir_path, dts_path, dataset required. 
The changes i did, is shown in the ss with red lines.
I gave the path files as default and file names at left top

'dirt_path', default = ucf101 video dataset
'dts_path', default = empty file for create jpgs
'dataset' i changed as default= 'ucf101'

![Ekran görüntüsü 2021-04-10 172229](https://user-images.githubusercontent.com/82275408/114273253-fa5e1480-9a21-11eb-9718-4589fcfdb2cd.png)

**Comment by guilhermesurek** [comment]
You should put "--" in front of the variable names to make then optional, like this '--dir_path', '--dst_path' and '--dataset'.

**Comment by EmirhanToprak** [comment]
It worked, thank you for reply 👍
