### ISSUE TITLE
Pretrained ActivityNet

### ISSUE THREAD

**Issue by hongyuanzhu** [kenshohara/3D-ResNets-PyTorch#3]
Dear Kensho

Thanks for your github, which is very useful for the community!  I wonder if any pre-trained ActivityNet model could be downloaded?

Thanks & Bests

OM

**Comment by kenshohara** [comment]
Hi,
Thank you for your interest in this work.
I plan to upload other models including pre-trained on ActivityNet at next month or earlier.
Please wait until then.

**Comment by rambleramble** [comment]
Just want to follow-up and see if the pre-trained models using ACtivityNet are available? Thanks
