### ISSUE TITLE
No checkpoint saved

### ISSUE THREAD

**Issue by cryptedp** [kenshohara/3D-ResNets-PyTorch#31]
I am running the command of the readme 

python main.py --root_path ~/data --video_path kinetics_videos/jpg --annotation_path kinetics.json \
--result_path results --dataset kinetics --model resnet \
--model_depth 34 --n_classes 400 --batch_size 128 --n_threads 4 --checkpoint 5

(with my options), but somehow if I check in my results folder, where opts.json and stuff is saved, there is no pth file saved, even after 100 epochs of training. Do I have to specify the checkpoint path too when calling main.py ?

**Comment by kenshohara** [comment]
The checkpoints (.pth files) are saved in result_path without any specific options.
Are ```train.log, train_batch.log, val.log``` saved?
Are logs of training and validation saved in these files?

**Comment by cryptedp** [comment]
Yes they are saved in the results folder but no checkpoint files are saved there...

**Comment by kenshohara** [comment]
Do you mean that ```train.log``` includes the log from epoch 1 to epoch 100 but any checkpoints are not saved?
Could you confirm that ```torch.save(states, save_file_path)``` in ```train.py``` is actually executed?

**Comment by TitaniumOne** [comment]
I meet the same problem too, do you have delt with it?
