### ISSUE TITLE
keyerror when loading pretrained model

### ISSUE THREAD

**Issue by chandnikathuria1992** [kenshohara/3D-ResNets-PyTorch#32]
hi dear
when i tried to run command:
python main.py --root_path ~/data --video_path ucf101_videos/jpg --annotation_path ucf101_01.json \
--result_path results --dataset ucf101 --n_classes 400 --n_finetune_classes 101 \
--pretrain_path models/resnet-34-kinetics-cpu.pth --ft_begin_index 4 \
--model resnet --model_depth 34 --resnet_shortcut A --batch_size 128 --n_threads 4 --checkpoint 5

i have also set no_cuda=True in opts as i m running it on cpu only**

I m getting this error:

Traceback (most recent call last):
  File "HAR_3D/main.py", line 47, in <module>
    model, parameters = generate_model(opt)
  File "/home/chandni/HAR_3D/model.py", line 178, in generate_model
    model.load_state_dict(pretrain['state_dict'])
  File "/home/chandni/anaconda3/envs/har/lib/python3.6/site-packages/torch/nn/modules/module.py", line 522, in load_state_dict
    .format(name))
KeyError: 'unexpected key "module.conv1.weight" in state_dict'

any idea to resolve this issue

**Comment by kenshohara** [comment]
Thank you for your comment.
It seems the finetuning of cpu version models includes some bugs.
I have to fix them.
Please wait the fixed version.

**Comment by chandnikathuria1992** [comment]
Have u used multiple GPUs while training for other models?

**Comment by kenshohara** [comment]
I fixed the bugs.
I also fix the model because the previous uploaded one includes nn.DataParallel.
Please download the latest codes and ```resnet-34-kinetics-cpu.pth```.

All models are trained by using multiple GPUs.

**Comment by chandnikathuria1992** [comment]
Thanks alot !
