### ISSUE TITLE
RuntimeError: invalid argument 1: must be strictly positive at /opt/conda/conda-bld/pytorch_1518243271935/work/torch/lib/TH/generic/THTensorMath.c:2247

### ISSUE THREAD

**Issue by chandnikathuria1992** [kenshohara/3D-ResNets-PyTorch#36]
Hi dear
Need help....on running main.py ,everything is going well till dataset loading as shown below:
model generated 
dataset loading [0/9537]
dataset loading [1000/9537]
dataset loading [2000/9537]
dataset loading [3000/9537]
dataset loading [4000/9537]
dataset loading [5000/9537]
dataset loading [6000/9537]
dataset loading [7000/9537]
dataset loading [8000/9537]
dataset loading [9000/9537]
dataset loading [0/3783]
dataset loading [1000/3783]
dataset loading [2000/3783]
dataset loading [3000/3783]
run

**error occured here:**

train at epoch 1
Traceback (most recent call last):
  File "/media/psrana/New Volume/chandni/HAR_3D_TU/main.py", line 139, in <module>
    train_logger, train_batch_logger)
  File "/media/psrana/New Volume/chandni/HAR_3D_TU/train.py", line 22, in train_epoch
    for i, (inputs, targets) in enumerate(data_loader):
  File "/home/psrana/anaconda3/envs/har_chandni/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 417, in __iter__
    return DataLoaderIter(self)
  File "/home/psrana/anaconda3/envs/har_chandni/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 242, in __init__
    self._put_indices()
  File "/home/psrana/anaconda3/envs/har_chandni/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 290, in _put_indices
    indices = next(self.sample_iter, None)
  File "/home/psrana/anaconda3/envs/har_chandni/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 119, in __iter__
    for idx in self.sampler:
  File "/home/psrana/anaconda3/envs/har_chandni/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 50, in __iter__
    return iter(torch.randperm(len(self.data_source)).long())
RuntimeError: invalid argument 1: must be strictly positive at /opt/conda/conda-bld/pytorch_1518243271935/work/torch/lib/TH/generic/THTensorMath.c:2247

what could be the

**Comment by kenshohara** [comment]
The path of dataset directory is correct?
I think this is the error caused by wrong video_path.

**Comment by chandnikathuria1992** [comment]
But it is loading data welll...after that run time error occurs. Argument
must be postive...could this be related to frames i have extracted..
During frame extraction there ws some warning message depricated pixel
format...
Actually i am first trying to understand acttion recognition with help of
ur work...
And now i m stucked here..So i request u to please help on this..

**Comment by kenshohara** [comment]
Did you confirm the video_path?
If your video_path is correct, your video dataset includes other problems.
Which dataset did you use?
Did you preprocess for the dataset according to the steps described in README.md?

**Comment by vateye** [comment]
Same runtime error.
dataset loading [0/3570]
dataset loading [1000/3570]
dataset loading [2000/3570]
dataset loading [3000/3570]
dataset loading [0/1530]
dataset loading [1000/1530]
run
train at epoch 1
Epoch: [1][1/112]	Time 4.807 (4.807)	Data 2.836 (2.836)	Loss 3.9053 (3.9053)	Acc 0.000 (0.000)
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [26,0,0] Assertion `t >= 0 && t < n_classes` failed.
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generated/../THCReduceAll.cuh line=339 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "main.py", line 137, in <module>
    train_logger, train_batch_logger)
  File "/media/ole/Document/Ubuntu/Research/3D-ResNets-PyTorch/train.py", line 31, in train_epoch
    acc = calculate_accuracy(outputs, targets)
  File "/media/ole/Document/Ubuntu/Research/3D-ResNets-PyTorch/utils.py", line 58, in calculate_accuracy
    n_correct_elems = correct.sum().data[0]
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generated/../THCReduceAll.cuh:339
terminate called after throwing an instance of 'std::runtime_error'
  what():  cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generic/THCStorage.c:184

How can I fix this?

**Comment by chandnikathuria1992** [comment]
Reduce batch size..it will work

**Comment by kenshohara** [comment]
@vateye 
This isn’t not the same error.
Did you correctly set n_classes?

**Comment by vateye** [comment]
For the HMDB51, I set the finetune class number 51, I think it’s not the n_classes’s problem.

**Comment by kenshohara** [comment]
Hmm... Anyway, your error is a different topic.
Please open a new issue.

**Comment by gwangaj** [comment]
@chandnikathuria1992 
Hi, could you please tell me how did you solve the problem? I encountered the same problem.

**Comment by chandnikathuria1992** [comment]
I changed video path...

**Comment by cc786537662** [comment]
same error here,indeed my --video_path is wrong:
check your configure carefully

**Comment by atuldsprimefocus** [comment]
I am also getting the same error, is anybody can suggest me the solution even though the video_path is correct

thanks
