### ISSUE TITLE
what should i do if i wanna evaluate this model on my own dataset ?

### ISSUE THREAD

**Issue by FesianXu** [kenshohara/3D-ResNets-PyTorch#37]
Hi kenshohara !
I want to evaluate this model on my own dataset without modifying too much the code. I have skimmed through the code and then i think i should modify the file `dataset.py`. However i dont know how to begin to modify it. Would you please give me some suggestions ? Thanks

**Comment by FesianXu** [comment]
Also, I noticed that the class annotation is loaded in `json` files and the file seems to be generated by `utils/hmdb51_json.py` and so on. However there is no introduction  about those files. Would you please introduce those files or tell me how to generate the json files of my new dataset. Thanks

**Comment by kenshohara** [comment]
Yes, you should implement your own ```yourdataset.py```.
For details, please read some documents for dataset class of pytorch.
This tutorial may be useful for you.
http://pytorch.org/tutorials/beginner/data_loading_tutorial.html

The json file is not needed.
You can use any file format if you implement your own dataset class.

**Comment by Fazlik995** [comment]
@FesianXu, hi

Could you implement your custom dataset?

If so, how did you solve issue with json file?

thank you.

**Comment by FesianXu** [comment]
@Fazlik995 Hi
The problem was a long time before and I can't find the project files now. But I think kenshohara already gives a good explanation about the method about custom dataset implementation. 
First the json files are only a way of label annotation so if your own datasets are simply some action label or something like that, just ignore the json files, maybe name your sample files like:
`A01_P01_V01.avi` would help you in later `dataset customing`. (`Axx` for action label, `Pxx` for person id and `Vxx` for view id for example.)
Second, to make a custom dataset, you just need to follow the intructions in: 
http://pytorch.org/tutorials/beginner/data_loading_tutorial.html
make sure that the custom class method `__getiem__` would return the items you need (e.g. sample matrix and labels), always you need to sparse the sample's name here to get the corresponding sample's label, And that is how the json files work here - to get the corresponding label in a formatting way.

So the conclusion is that, you don't have to use the json files.

**Comment by slighting666** [comment]
@FesianXu @Fazlik995 
Hi, I got the accuracy of val.log, but I want to calculate the accuracy of video level, where can I get the val.json file and how to use eval_ucf101.py?

**Comment by Fazlik995** [comment]
@FesianXu thank you for.

**Comment by Fazlik995** [comment]
@slighting666 

If you got val.log then run command below:
python main.py --resume_path ''result_path/save200.pth" --no_train --no_val --test --test_subset val

in result_path you will receive val.json file.

Then add below code to eval_ucf101.py:
if __name__ == '__main__':
    ucf = UCFclassification('/home/fazlik/Desktop/3D-ResNets- PyTorch/ucfTrainTestlist/ucf101_01.json', '/home/fazlik/Desktop/3D-ResNets-PyTorch/result/MUNet_result/val.json', subset ='validation', top_k=1)
    ucf.evaluate()
    print(ucf.hit_at_k)

Last,  run utils/eval_ucf101.py

**Comment by slighting666** [comment]
@Fazlik995  ok，thanks!
Clip level is a video that randomly selects the beginning in time and then 16 consecutive frames. I want to know how many clips are extracted from a video？

**Comment by sebyo** [comment]
I've tried to work with my dataset that have the same structure as the ucf101 so I convert to json file  but got an error while starting the training : line 85: --makedataset-- keyError ' classename ' I didn't know what's the problem ?
can anyone help me ?
