### ISSUE TITLE
regarding batch_size

### ISSUE THREAD

**Issue by chandnikathuria1992** [kenshohara/3D-ResNets-PyTorch#38]
Hi dear
can u please tell about how to choose batch size?
My system has one GPU(8 GB memory) and System memory is 64 GB.
when i tried to run with default batch size of 128 , it gave run time error: out of memory
Then i reduced it to 20, it started working.
But i want to know what should be appropriate batch size according to my system configuration, little about how to set appropriate batch size and whether it will affect accuracy?
I would be very much thankful for your suggestion on this....

**Comment by kenshohara** [comment]
I did not conduct experiments for searching the best batch size,
but I think it should be large like 128 and 256.
In preliminary experiments using ResNet-34 trained on ActivityNet,
using batch size 128 achieved better accuracies than smaller one.
If you have only one GPU, you should use batch size as large as possible.

**Comment by chandnikathuria1992** [comment]
Thanks
