### ISSUE TITLE
val.json file

### ISSUE THREAD

**Issue by chandnikathuria1992** [kenshohara/3D-ResNets-PyTorch#46]
Hi dear
Can u please upload your val.json for ucf101 split-1?

**Comment by chandnikathuria1992** [comment]
Thanks

**Comment by slighting666** [comment]
@chandnikathuria1992 
Hi, I got the accuracy of val.log, but I want to calculate the accuracy of video level, where can I get the val.json file and how to use eval_ucf101.py?

**Comment by Fazlik995** [comment]
@kenshohara 

what is your command to get val.json file 

Please, could you provide that command?

Thank you
