### ISSUE TITLE
error_of_--resume

### ISSUE THREAD

**Issue by liu666666** [kenshohara/3D-ResNets-PyTorch#5]
Thanks for your sharing! @kenshohara 
when i use the --resume, I met an error like this :
KeyError: 'missing keys in state_dict: "set([\'module.layer2.0.downsample.1.running_var\', \'module.layer3.0.downsample.1.running_var\', \'module.layer2.0.downsample.1.running_mean\', \'module.layer4.0.downsample.1.running_mean\', \'module.layer4.0.downsample.1.running_var\', \'module.layer3.0.downsample.1.weight\', \'module.layer2.0.downsample.0.weight\', \'module.layer3.0.downsample.0.weight\', \'module.layer4.0.downsample.0.weight\', \'module.layer4.0.downsample.1.bias\', \'module.layer4.0.downsample.1.weight\', \'module.layer3.0.downsample.1.bias\', \'module.layer2.0.downsample.1.weight\', \'module.layer2.0.downsample.1.bias\', \'module.layer3.0.downsample.1.running_mean\'])"'

Could you please tell how to debug it ?

**Comment by liu666666** [comment]
It seems that i figure it out.

**Comment by kenshohara** [comment]
I am grad that you solved the problem!

That error is caused by the difference between the loaded model and used model.
You must use the same parameter (model depth, shortcut_type, etc) as resume_path.
