### ISSUE TITLE
Accuracy of fine-tuning on UCF-101

### ISSUE THREAD

**Issue by mariankyoussef** [kenshohara/3D-ResNets-PyTorch#53]
Hello!
I got 85.2% when fine tuning resnet-50 on UCF-101 split-1 instead of 89%, my settings are:

python main.py --root_path ~/big/3D-ResNets-PyTorch --video_path ~/big/UCF-101_jpg --annotation_path utils/ucf101_01.json --result_path ucf101_results --dataset ucf101 --n_classes 400 --n_finetune_classes 101 --pretrain_path model_weights/resnet-50-kinetics.pth --ft_begin_index 4 --model resnet --model_depth 50 --resnet_shortcut B --batch_size 128 --n_threads 4 --checkpoint 5 --learning_rate 0.001

**Comment by mariankyoussef** [comment]
Yes it is, perfect thanks!

**Comment by mariankyoussef** [comment]
Excuse me, can I know how to generate val.json to get the same accuracy as
the paper? Can you upload the file? Thanks in advance!

Best Regards,
Marian
Graduate Teaching Assistant
Electronics and Communications Engineering Department
Arab Academy for Science, Technology, and Maritime Transport

**Comment by RyanCV** [comment]
@kenshohara how can I get val.json?

**Comment by RyanCV** [comment]
@kenshohara 
I used the following command (pretrained kinetics resnet34 fine tuned on ucf101) to do test and it generated val.json, 
`python main.py --root_path ./data --video_path ucf101_videos/jpg --annotation_path ucf101_01.json --result_path resnet_ms34_results --dataset ucf101 --model resnet_ms --model_depth 34 --n_classes 101 --batch_size 1 --n_threads 4 --pretrain_path resnet_ms34_results/save_200.pth --no_train --no_val --test --test_subset val --resnet_shortcut A --n_finetune_classes 101
`
But, when I use val.json and utils/eval_ucf101.py to calculate the accuracy, it gave me very low accuracy, which was 0.01. It's not accurate. In the val.log, I found the accuracy is about 0.8, do you know why this accuracy is too low? Thanks.

**Comment by fnj1017** [comment]
Hi, may I know how to get val.json and how to use the evaluation script?

I am only having val.log file

Thanks.

**Comment by BarakBat** [comment]
The val.json is created by running test.py

**Comment by ilovekj** [comment]
> Is the accuracy clip-accuracy that is output in val.log?
> If it true, it is the correct result.
> The accuracy reported in my paper is video-accuracy that is evaluated by using val.json and utils/eval_ucf101.py.



> Hello!
> I got 85.2% when fine tuning resnet-50 on UCF-101 split-1 instead of 89%, my settings are:
> python main.py --root_path ~/big/3D-ResNets-PyTorch --video_path ~/big/UCF-101_jpg --annotation_path utils/ucf101_01.json --result_path ucf101_results --dataset ucf101 --n_classes 400 --n_finetune_classes 101 --pretrain_path model_weights/resnet-50-kinetics.pth --ft_begin_index 4 --model resnet --model_depth 50 --resnet_shortcut B --batch_size 128 --n_threads 4 --checkpoint 5 --learning_rate 0.001

excuse me, how to get 80%+ acc? I followed this paper,but I can only get 30%+ on val when I trained 60 epoch

**Comment by slighting666** [comment]
@Esaada   hello！
I used test.py to generate val. Log, but I ran main.py and got an error. Can you help me?
Traceback (most recent call last):
  File "D:/github/3D resnet/3D resnet/main.py", line 163, in <module>
    test.test(test_loader, model, opt, test_data.class_names)
  File "D:\github\3D resnet\3D resnet\test.py", line 52, in test
    test_results, class_names)
  File "D:\github\3D resnet\3D resnet\test.py", line 20, in calculate_video_results
    'label': class_names[locs[i]],
KeyError: tensor(1)
