### ISSUE TITLE
How to compute the accuracy?

### ISSUE THREAD

**Issue by JincanDeng** [kenshohara/3D-ResNets-PyTorch#55]
I have finetuned the resnet50 model in UCF-101 datasets.
And I run the test code by setting the flag 'no_train', 'no_eval', 'test'. And I finally got a file named val.json.
But how can I get the test accuracy?

**Comment by kenshohara** [comment]
#53 is the same issue as yours.

**Comment by RyanCV** [comment]
@kenshohara In the eval_ucf101.py, I add 
```
if __name__ == '__main__':
    #pdb.set_trace()
    ucf_classification = UCFclassification('data/ucf101_01.json', 'data/results/val.json', subset='validation', top_k=1)
    ucf_classification.evaluate()
    print(ucf_classification.hit_at_k)
```
But, I got the following errors, how to solve it? thanks.
`3D-ResNets-PyTorch# python utils/eval_ucf101.py`

> /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
>   return f(*args, **kwds)
> /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
>   return f(*args, **kwds)
> Traceback (most recent call last):
>   File "utils/eval_ucf101.py", line 164, in <module>
>     ucf_classification = UCFclassification('data/ucf101_01.json', 'data/results/val.json', subset='validation', top_k=1)
>   File "utils/eval_ucf101.py", line 23, in __init__
>     ground_truth_filename)
>   File "utils/eval_ucf101.py", line 59, in _import_ground_truth
>     for videoid, v in data['database'].iteritems():
> AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by BarakBat** [comment]
replace :iteritems with items
