### ISSUE TITLE
RuntimeError: expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by hareeshdevarakonda** [kenshohara/3D-ResNets-PyTorch#56]
Traceback (most recent call last):
  File "main.py", line 129, in <module>
    train_logger, train_batch_logger)
  File "/home/hareesh/Downloads/3D-ResNets-PyTorch-master/train.py", line 22, in train_epoch
    for i, (inputs, targets) in enumerate(data_loader):
  File "/home/hareesh/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/home/hareesh/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/hareesh/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/hareesh/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/hareesh/Downloads/3D-ResNets-PyTorch-master/datasets/ucf101.py", line 193, in __getitem__
    clip = torch.stack(clip, 0).permute(1, 0, 2, 3)
RuntimeError: expected a non-empty list of Tensors

Please let me know cause of this error.

**Comment by kenshohara** [comment]
Did you correctly set video_path?

**Comment by hareeshdevarakonda** [comment]
Yeah, Video path is fine added one function in code its running now

##Added Funtion

def loadImages(path, indecies):
    # return array of images

    loadedImages = []
    #print ("path",path," indecies",indecies)
    for image in indecies:
        if image < 10:
            img = PImage.open(path + '/' + 'frame00000' + str(image) + '.jpg')    
        elif image < 100:
            img = PImage.open(path + '/' + 'frame0000' + str(image) + '.jpg')
        elif image < 1000:
            img = PImage.open(path + '/' + 'frame000' + str(image) + '.jpg')
        elif image < 10000:
            img = PImage.open(path + '/' + 'frame00' + str(image) + '.jpg')
        else:
            img = PImage.open(path + '/' + 'frame0' + str(image) + '.jpg')

        loadedImages.append(img)

    return loadedImages

**Comment by ll490187880** [comment]
Hello~Where to put your new function?

**Comment by ll490187880** [comment]
Hello~Where to put your new function? @hareeshdevarakonda

**Comment by hareeshdevarakonda** [comment]
@ll490187880  No need to keep any new function keep running the same code on pythorch 0.4 version n make sure of your annotation of the images i have annotations like "frame000000" according to this code annotations are like "image_000000". please make sure of these things

**Comment by gycka** [comment]
@hareeshdevarakonda I tried with the original code and with the included function; however, I got the same error. My path to files is correct, the names are also correct (frame000000). Any suggestions for moving forward (I understand it has been a year since your comment).

**Comment by shadsakib** [comment]
Hi. Was the problem solved? Thank you.

**Comment by TitaniumOne** [comment]
I meet the same problem. How do you solve it? Thank you!

**Comment by liuzhaoo** [comment]
> I meet the same problem. How do you solve it? Thank you!
Hi，buddy，Do you have any solution？

**Comment by TitaniumOne** [comment]
有点忘记了，可能是在get training data里面改一些东西。用print检查检查




| |
lh
邮箱：liuhao610216579@163.com
|

签名由 网易邮箱大师 定制

On 10/15/2020 11:15, 刘钊 wrote:

I meet the same problem. How do you solve it? Thank you!
Hi，buddy，Do you have any solution？

**Comment by liuzhaoo** [comment]
在训练的时候是没问题的，但是每个epoch训练完进行验证的时候就会报错。我在VideoDatasetMultiClips 里的__getitem__中打印clips  但是输出并没有这一项。如果你能想起更多东西，麻烦告诉我一下，谢谢！ 415091lz 邮箱415091lz@gmail.com 签名由 网易邮箱大师 定制 On 10/15/2020 11:32, Hao Liu wrote: 有点忘记了，可能是在get training data里面改一些东西。用print检查检查 | | lh 邮箱：liuhao610216579@163.com | 签名由 网易邮箱大师 定制 On 10/15/2020 11:15, 刘钊 wrote: I meet the same problem. How do you solve it? Thank you! Hi，buddy，Do you have any solution？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
