### ISSUE TITLE
Test set Kinetics

### ISSUE THREAD

**Issue by fabienbaradel** [kenshohara/3D-ResNets-PyTorch#6]
Hi,

Thanks for releasing this awesome repository. However I cannot find the test set son file (matching the youtube_id to a label) on the Kinetics dataset webpage.
Could you show where to find it?

Thanks

**Comment by kenshohara** [comment]
Hi,

The test set does not include class labels.
To evaluate results on the test sets,
you have to use the [evaluation server](http://activity-net.org/challenges/2017/evaluation.html).

**Comment by fabienbaradel** [comment]
Thanks for your quick response, i'll make it like that ;)
