### ISSUE TITLE
Testing error on UCF-101

### ISSUE THREAD

**Issue by hareeshdevarakonda** [kenshohara/3D-ResNets-PyTorch#60]
/home/hareesh/Downloads/3D-ResNets-PyTorch-master/test.py:42: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  inputs = Variable(inputs, volatile=True)
/home/hareesh/Downloads/3D-ResNets-PyTorch-master/test.py:45: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  outputs = F.softmax(outputs)
[1/5607]	Time 0.723 (0.723)	Data 0.620 (0.620)	
Traceback (most recent call last):
  File "main.py", line 154, in <module>
    test.test(test_loader, model, opt, test_data.class_names)
  File "/home/hareesh/Downloads/3D-ResNets-PyTorch-master/test.py", line 50, in test
    test_results, class_names)
  File "/home/hareesh/Downloads/3D-ResNets-PyTorch-master/test.py", line 20, in calculate_video_results
    'label': class_names[locs[i]],
KeyError: tensor(92)

Command I used: python3 main.py --root_path ~/home/hareesh/Downloads/3D-ResNets-PyTorch-master/ --video_path /home/hareesh/Downloads/UCF101jpeg/ --annotation_path /home/hareesh/Downloads/UCF_list/ucf101_01.json \--result_path /home/hareesh/Downloads/3D-ResNets-PyTorch-master/results --dataset ucf101 --n_classes 101 --n_finetune_classes 101 \--resume_path /home/hareesh/Downloads/3D-ResNets-PyTorch-master/results/save_50.pth --resnext_cardinality 32 --ft_begin_index 4 \--model resnext --model_depth 101 --resnet_shortcut B --batch_size 8 --n_threads 4 --checkpoint 5 --no_val --no_train --test

**Comment by songzenghui** [comment]
Hi ,how do solve it?
I have the same problem

**Comment by hareeshdevarakonda** [comment]
try pytorch 0.3x version that should work. this is because of version compatibility
