### ISSUE TITLE
use myself dataset to train

### ISSUE THREAD

**Issue by XIWuXueWei** [kenshohara/3D-ResNets-PyTorch#64]
when i use myself dataset to train rexnext-101, input size:[batch_size, 3, 16, 112, 112], but in self.fc layer
have a error size mismatch [batch_size, 8192] m1, [2048, my n_classes] m2.

**Comment by kenshohara** [comment]
How do you execute, and what version of python and pytorch do you use?

**Comment by XIWuXueWei** [comment]
i execute like the issue "train on UCF101split 1", and I use python 2.7(anaconda) and pytorch 0.3.1

**Comment by kenshohara** [comment]
You should use python3.
I don't officially support python3.
