### ISSUE TITLE
train on UCF101split 1

### ISSUE THREAD

**Issue by yuhuixu1993** [kenshohara/3D-ResNets-PyTorch#65]
Hi, thank you for you code, I try to use your code to train on UCF101 from scratch. Bur following problem occurs.
RuntimeError: size mismatch, m1: [128 x 2048], m2: [512 x 101] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:249

My code is 
python main.py --root_path /home/xuyuhui/code/data/ --video_path /home/xuyuhui/code/data/UCF101/jpg --annotation_path ucf101_01.json --result_path results --dataset ucf101 --model resnet --model_depth 34 --n_classes 101 --batch_size 128 --n_threads 4 --checkpoint 5

Thanks!

**Comment by kenshohara** [comment]
I tried to execute using the same options,
but it correctly worked.
What versions of python and pytorch do you use?

**Comment by XIWuXueWei** [comment]
Hi,  Have you solved the problem?

**Comment by yuhuixu1993** [comment]
I used python 2.7 and pytorch 0.3

**Comment by yuhuixu1993** [comment]
This problem is caused by the python version, python3 would work

**Comment by kenshohara** [comment]
Yes, you should use python3.
I don't officially support python2.
