### ISSUE TITLE
Could I share your trained ResNeXt101 models for splits2 and split3 on HMDB51 and UCF101?

### ISSUE THREAD

**Issue by junmuzi** [kenshohara/3D-ResNets-PyTorch#69]
@kenshohara ,

Would you will provide trained ResNeXt101 models for split2 and splits on HMDB51 and UCF101 dataset?

I am so interested in your work. Could I share your trained models as follows:

resnext-101-64f-kinetics-hmdb51_split2.pth
resnext-101-64f-kinetics-hmdb51_split3.pth
resnext-101-64f-kinetics-ucf101_split2.pth
resnext-101-64f-kinetics-ucf101_split3.pth
resnet-18-kinetics-hmdb51_split1.pth
resnet-18-kinetics-ucf101_split1.pth

Seems I could reproduce the paper's results in Table 5 for ResNeXt-101(64f) only when I have trained models for split2 and split3. Thank you very much!

Cool! That's great, you have provided resnext-101-64f-kinetics-hmdb51_split1.pth and resnext-101-64f-kinetics-ucf101_split1.pth. 

The follows is my testing sharing(using the authors providing models):
+-------------------------------------------------------+-------------------------------------------+
| Models                                                                      |      UCF-101             |          HMDB-51     |
+-------------------------------------------------------+----------------------+--------------------+
| resnext-101-64f-kinetics-hmdb51_split1.pth            |           None             |             71.24         |
+-------------------------------------------------------+----------------------+--------------------+
| resnext-101-64f-kinetics-ucf101_split1.pth              |           94                   |             None         |
+-------------------------------------------------------+----------------------+--------------------+

**Comment by kenshohara** [comment]
I shared the files by email, right?

**Comment by junmuzi** [comment]
@kenshohara ,

Yes, Thank you very much. Sorry for trouble you again. Could I share your trained  
resnet-152-kinetics-ucf101_split1.pth and  resnet-152-kinetics-hmdb51_split1.pth models? 

Thank you very much. :-)

**Comment by BarakBat** [comment]
@junmuzi  Hi, I'm trying to reproduce the results on hmdb51, but I'm getting much higher results, have you seen something like this?

**Comment by jinwchoi** [comment]
Hi @kenshohara can you share the following models with me too?

resnext-101-64f-kinetics-hmdb51_split2.pth
resnext-101-64f-kinetics-hmdb51_split3.pth
resnext-101-64f-kinetics-ucf101_split2.pth
resnext-101-64f-kinetics-ucf101_split3.pth
resnet-18-kinetics-hmdb51_split1.pth
resnet-18-kinetics-ucf101_split1.pth

**Comment by Cong222** [comment]
@kenshohara @junmuzi Could you send those to me? Thank lots!

**Comment by slighting666** [comment]
@junmuzi @kenshohara @Cong222 
hello，Could you send those to me? Thank lots!
