### ISSUE TITLE
Out of memory in validation and test

### ISSUE THREAD

**Issue by ziweizhao1993** [kenshohara/3D-ResNets-PyTorch#72]
Hi,

I am testing ResNeXt-101(64f) on TITAN X × 8, with Torch 0.4.0, python 3.6 and cuda 8.0.
I used a batch size of 96, it went well during training, but got a memory error during validation and test.

The command I used is:
python main.py --root_path . --video_path UCF_JPG_frames --annotation_path ucf101_01.json --result_path output --dataset ucf101 --model resnext --model_depth 101 --n_classes 400 --batch_size 96 --n_threads 4 --pretrain_path resnext-101-64f-kinetics.pth --resnet_shortcut B --sample_duration 64 --ft_begin_index 4 --n_finetune_classes 101 --n_epochs 100 --weight_decay 1e-5 --test

Memory usage before the crash:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 387.34             Driver Version: 387.34             |
|-------------------------------+----------------------+----------------------+
|   0  TITAN Xp            Off  | 00000000:04:00.0 Off |                  N/A |
| 34%   53C    P2    84W / 250W |  11767MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN Xp            Off  | 00000000:05:00.0 Off |                  N/A |
| 36%   56C    P2    80W / 250W |  11879MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  TITAN Xp            Off  | 00000000:08:00.0 Off |                  N/A |
| 38%   59C    P2    83W / 250W |  11879MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  TITAN Xp            Off  | 00000000:09:00.0 Off |                  N/A |
| 35%   53C    P2    71W / 250W |  11879MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  TITAN Xp            Off  | 00000000:84:00.0 Off |                  N/A |
| 37%   56C    P2    79W / 250W |  11879MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  TITAN Xp            Off  | 00000000:85:00.0 Off |                  N/A |
| 39%   59C    P2    74W / 250W |  11879MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  TITAN Xp            Off  | 00000000:88:00.0 Off |                  N/A |
| 34%   52C    P2    71W / 250W |  11879MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  TITAN Xp            Off  | 00000000:89:00.0 Off |                  N/A |
| 38%   58C    P2    72W / 250W |  11879MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

Is this normal?

Thank you.

**Comment by kenshohara** [comment]
I think it is normal.
When I train the model, I used batch size=64.
