### ISSUE TITLE
No module named models

### ISSUE THREAD

**Issue by Zhuysheng** [kenshohara/3D-ResNets-PyTorch#74]
whats the problem when i run 
zys@amax:~/Downloads/3D-ResNets-PyTorch$ python main.py --root_path ~/Downloads/3D-ResNets-PyTorch/data --video_path ucf101_videos/jpg --annotation_path ucf101_01.json --result_path results --dataset ucf101 --n_classes 400 --n_finetune_classes 101 --pretrain_path models_weights/resnet-34-kinetics.pth --ft_begin_index 4 --model resnet --model_depth 34 --resnet_shortcut A --batch_size 128 --n_threads 4 --checkpoint 5

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from model import generate_model
  File "/home/zys/Downloads/3D-ResNets-PyTorch/model.py", line 4, in <module>
    from models import resnet, pre_act_resnet, wide_resnet, resnext, densenet
ImportError: No module named models

**Comment by hleu** [comment]
Did you try export PYTHONPATH=$PYTHONPATH:path/to/models ?
In your case I think it should be: 
export PYTHONPATH=$PYTHONPATH:/home/zys/Downloads/3D-ResNets-PyTorch/

**Comment by kenshohara** [comment]
Are there the all files and directories in ~/Downloads/3D-ResNets-PyTorch?

**Comment by Zhuysheng** [comment]
@hleu @kenshohara   thanks, i just solved. it work by using python3
