### ISSUE TITLE
while kinetics test, error occurs.

### ISSUE THREAD

**Issue by lee2h** [kenshohara/3D-ResNets-PyTorch#75]
in dataset.py

line 114
sample_stride=opt.sample_stride

but,  in datasets/kinetics.py

line 140, class Kinetics(data.Dataset):

has no input space for sample_stride.

Traceback (most recent call last):
  File "main.py", line 154, in <module>
    target_transform)
  File "dataset.py", line 112, in get_test_set
    sample_stride=opt.sample_stride)
AttributeError: 'Namespace' object has no attribute 'sample_stride'

does sample stride have no effect on the results?

**Comment by hleu** [comment]
Did you try the solution mentioned at the bottom of #33?

**Comment by lee2h** [comment]
@hleu 
is sample_stride not used?
this is what I understand.
