### ISSUE TITLE
Size of Kinetics dataset

### ISSUE THREAD

**Issue by hleu** [kenshohara/3D-ResNets-PyTorch#77]
If it is not too much trouble, could you please let me know the approximate size of the Kinetics dataset? I used the provided crawler and have been downloading the dataset for some time on a Power machine and it is still at around 90GB. I know that you mentioned it is several hundred of GB but I just want to have some ideas of where I am and how much time it will take to fully download the dataset. Thank you.

**Comment by lee2h** [comment]
approximately, the dataset's size is 400GB.

**Comment by AlexHu123** [comment]
what about the size when you extract all the frames? @lee2h
