### ISSUE TITLE
slimmer network for transferring to segmentation tasks

### ISSUE THREAD

**Issue by lfz** [kenshohara/3D-ResNets-PyTorch#78]
Hi, Thank you so much for the great work, I want to transfer your work to volumetric data segmentation tasks, but I found that 

1. the images are in  RGB format, but my data is grayscale. Well, it is easy to change the weight of the pretrained model. But I still want to know wether you can train a grayscale model to make it more convenient for us.

2. In 3d segmentation, the memory consumption is so huge, so that I cant afford such a huge network, could you kindly supply us with a slimmer model so that I can try to fully convolutionalize it?

Thank you

**Comment by kenshohara** [comment]
I'm sorry but currently, I don't have a plan to supply additional models.
