### ISSUE TITLE
finetune on custom dataset

### ISSUE THREAD

**Issue by nationalflag** [kenshohara/3D-ResNets-PyTorch#9]
I have a small two classes dataset, which have 1000 videos for each class. I want to use finetune your pretrained models, but it seems to overfit my dataset. How can i figure it out? Enlarge my dataset?

**Comment by kenshohara** [comment]
I think 2000 videos dataset can be used for fine-tuning.
To avoid overfitting, you should fine-tune a part of models, such as only last fc layer.
--ft_begin_index option control how much layer is fine-tuned.
In our experiments on UCF-101 and HMDB-51,
fine-tuning only conv5_x and fc achieved the best results.

**Comment by prabhatkumar95** [comment]
@nationalflag how did you prepare your dataset.

**Comment by pranavgundewar** [comment]
Even I would like to know how to prepare the dataset
