### ISSUE TITLE
Pretrain models cannot download

### ISSUE THREAD

**Issue by KeCh96** [kenshohara/3D-ResNets-PyTorch#94]
Hello, I am making a demo about 3D convolution network. After reading your CVPR paper, I am happy to use your pretrain models. 
However, when I try to open [your link](https://drive.google.com/drive/folders/14KRBqT8ySfPtFSuLsFS2U4I-ihTDs0Y9?usp=sharing), I get "The folder has been put in the recycle bin.". These pretrain models are extramely important for my program, because I don't have many GPU to train the network from scratch. Please give me a chance to use res3D convolution network...... @kenshohara

**Comment by chaofiber** [comment]
I am also a learner in c3d network and really need the pretrained models. please give me a chance to use your models.  @kenshohara 
Thanks very much in advance.

**Comment by landersson** [comment]
+1

**Comment by tianmaliuixing** [comment]
+1, I can't find the pretrain model.....

**Comment by kenshohara** [comment]
I'm sorry. I think it was some operation mistakes.
I upload the files again soon.

**Comment by kenshohara** [comment]
I uploaded the files.
Please confirm!

**Comment by tianmaliuixing** [comment]
Have you updated the links?I still can't open the url....

**Comment by kenshohara** [comment]
I also updated the link now!

**Comment by bandontseng** [comment]
Thanks! The pretrained models can be downloaded now.
